export const PROFILE_PHOTO = "/sales-doc/uploads/2026/05/82eb66a3fa60b3f306af1c2a.jpg";

export const SKILL_GROUPS = [
  {
    title: "AI Engineering",
    items: [
      "AI-разработка",
      "AI-агенты",
      "AI workflow",
      "AI automation",
      "AI-помощники",
      "MCP",
      "API / REST API",
      "Webhooks",
      "JSON",
      "OpenRouter",
      "OpenAI",
      "Claude",
      "DeepSeek",
      "Gemini",
      "n8n",
      "Activepieces",
      "Flowise",
      "Langflow",
      "Node-RED",
      "Python",
      "TypeScript",
      "Next.js",
      "React",
      "PostgreSQL / MySQL",
      "Supabase",
      "Docker",
      "VPS",
      "Nginx",
      "PM2",
    ],
  },
  {
    title: "Web / Digital products",
    items: [
      "Сайты",
      "Лендинги",
      "SaaS",
      "Веб-приложения",
      "UI/UX",
      "Веб-дизайн",
      "UX-аудит",
      "Конверсионные страницы",
      "SEO-аудит",
      "Анализ конкурентов",
      "Архитектура цифровых продуктов",
      "Vibe Coding",
      "AI-assisted development",
      "Проектирование MVP",
    ],
  },
  {
    title: "Visual content",
    items: [
      "Дизайн карточек товаров",
      "Ozon",
      "Wildberries",
      "Avito",
      "Инфографика",
      "AI-фотографии",
      "Обработка фотографий",
      "AI image generation",
      "Работа с референсами",
      "Визуальные концепции",
      "Рекламные креативы",
      "Баннеры",
      "Презентации",
      "Коммерческие предложения",
    ],
  },
  {
    title: "Art / Illustration",
    items: [
      "Художник",
      "Иллюстрация",
      "Цифровая иллюстрация",
      "Картины",
      "Аэрография",
      "Рисунок",
      "Визуальная композиция",
      "Работа с цветом",
      "Концепт-арт",
    ],
  },
] as const;
