// Общие типы и константы для Lead Agent
export interface Radar { id: string; city: string; niche: string; filters: string[]; lastCheck?: string; leadCount: number; active: boolean; }
export interface Lead { id: string; domain: string; name: string; url: string; h1?: { count: number; texts: string[]; ok: boolean }; cms?: string | null; cmsTier?: string | null; contactName?: string | null; sent?: boolean; status?: string; hotScore: number; ssl?: { valid: boolean; daysRemaining: number; grade: string }; score: number; scorePercent: number; phone?: string; email?: string; problems: string[]; gradeColor: string; }
export interface PipelineLead { id: string; domain: string; name: string; url: string; phone?: string; email?: string; status: string; opened: boolean; }
export type EmailStatus = "idle" | "sending" | "checking" | "sent" | "error";
// Подсказки для ниш (не жёсткий список — пользователь может ввести свою)
export const NICHE_SUGGESTIONS = ["Стоматологии","Строительство","Кафе и рестораны","Автосервисы","Юристы","Клиники","Салоны красоты","Фитнес-клубы","Отели","Грузоперевозки","Интернет-магазины","Недвижимость","Бухгалтерия","Рекламные агентства","Туризм","Образование","Производство","IT-компании","Дизайн интерьера","Фотографы","Маркетинговые агентства","Производство мебели","Интерьерный декор","SEO-услуги","Разработка чат-ботов","Строительные компании","Франшизы","Любая B2B услуга"];
export const CITIES = ["Москва","Санкт-Петербург","Казань","Екатеринбург","Новосибирск","Краснодар","Ростов-на-Дону","Нижний Новгород","Челябинск","Самара"];
export const KP_TEMPLATE = `Здравствуйте!\n\nПровёл аудит вашего сайта [ДОМЕН]. Нашёл проблемы, которые влияют на клиентов:\n\n[ПРОБЛЕМЫ]\n\nЯ могу это исправить за 2-3 дня. Портфолио: <a href="https://konversus.ru/about">konversus.ru/about</a>\n\nЕсли интересно — напишите в <a href="https://t.me/bilarius">Telegram @bilarius</a> или позвоните <a href="tel:+79212013252">+7 921 201-32-52</a>.\n\nАлексей Тимофеев\nKonversus · 17 лет в digital`;
